### ISSUE TITLE
批量创建商品时经常会出现异常

### ISSUE THREAD

**Issue by jxzsxsp** [Hanson/youzan-sdk#15]
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Requ in /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Requ in /data/youzan_api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

**Comment by Hanson** [comment]
这个更多看似接口的问题

**Comment by jxzsxsp** [comment]
这个有什么方法可以解决吗？我异常处理也捕捉不到

**Comment by Hanson** [comment]
异常不会捕捉不到，截图代码吧

**Comment by jxzsxsp** [comment]
![image](https://user-images.githubusercontent.com/3166271/55372523-9e0fb280-5534-11e9-9f14-c83885b90ac7.png)

麻烦了

**Comment by jxzsxsp** [comment]
![image](https://user-images.githubusercontent.com/3166271/55372629-ffd01c80-5534-11e9-8fa0-317db4479af7.png)
异常信息截图

**Comment by Hanson** [comment]
你的异常代码没有表明是这行代码触发的
